import type { NextPage } from 'next'
import Head from 'next/head'
import Card from '../components/card'
import styles from '../styles/Home.module.css'
import { getRandomCard } from '../tasks/getCards'

const Home = ({imgUrl}: {imgUrl: string}) => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Card cardImgUrl={imgUrl}></Card>
    </div>
  )
}

export async function getServerSideProps() {
  const url: string = await getRandomCard();

  return {
    props: {imgUrl: url},
  }
}

export default Home
